repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v6.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: shellcheck
        entry: shellcheck --external-sources --shell=bash
        language: system
        name: shellcheck
        require_serial: true
        types: [executable, text]

  - repo: local
    hooks:
      - id: shfmt
        entry: shfmt -s -bn -sr -i 4 -w
        language: system
        name: shfmt
        require_serial: true
        types: [executable, text]

  # ----------------------------------------------------------------------------

exclude: |
  (?x)(
    ^CHANGELOG.md$
  )
