repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/frnmst/md-toc
    rev: '8.1.4'
    hooks:
      - id: md-toc
        args: [-p, -s, '1', github]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--prose-wrap, always, --single-quote]
        types_or: [markdown]

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: shellcheck
        entry: shellcheck --external-sources --shell=bash
        language: system
        name: shellcheck
        require_serial: true
        types: [executable, text]

  - repo: local
    hooks:
      - id: shfmt
        entry: shfmt -s -bn -sr -i 4 -w
        language: system
        name: shfmt
        require_serial: true
        types: [executable, text]

  # ----------------------------------------------------------------------------

exclude: |
  (?x)(
    ^CHANGELOG.md$
  )
